User mvc
JETFlex/AfternoonDelight pull request #3
Opened 2017-06-05 18:21 UTC by jilldela

Create user model, controller and jbuilder views.
Create session controller and application controller.

2017-06-05 23:31 UTC, eadams17 requested changes
fix model

2017-06-06 01:08 UTC, tylerreichle approved these changes

2017-06-06 01:16 UTC, tylerreichle approved these changes

2017-06-06 01:17 UTC, tylerreichle approved these changes

2017-06-06 01:17 UTC, tylerreichle approved these changes

2017-06-06 01:18 UTC, tylerreichle approved these changes

2017-06-06 01:18 UTC, eadams17 approved these changes

2017-06-06 01:18 UTC, merged